# Generated by Django 5.2.6 on 2025-09-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_story_video_alter_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='disable_comments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='hide_counts',
            field=models.BooleanField(default=False),
        ),
    ]
